/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_tuboroid_text_span_EntryAnchorFilter */

#ifndef _Included_info_narazaki_android_tuboroid_text_span_EntryAnchorFilter
#define _Included_info_narazaki_android_tuboroid_text_span_EntryAnchorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_narazaki_android_tuboroid_text_span_EntryAnchorFilter
 * Method:    gatherNative
 * Signature: (Ljava/lang/String;)[Linfo/narazaki/android/tuboroid/text/span/EntryAnchorSpanSpec;
 */
JNIEXPORT jobjectArray JNICALL Java_info_narazaki_android_tuboroid_text_span_EntryAnchorFilter_gatherNative(JNIEnv *,
        jobject, jstring);

/*
 * Class:     info_narazaki_android_tuboroid_text_span_EntryAnchorFilter
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_tuboroid_text_span_EntryAnchorFilter_initNative(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
