/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_lib_list_ListUtils */

#ifndef _Included_info_narazaki_android_lib_list_ListUtils
#define _Included_info_narazaki_android_lib_list_ListUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_narazaki_android_lib_list_ListUtils
 * Method:    split
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_info_narazaki_android_lib_list_ListUtils_split__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     info_narazaki_android_lib_list_ListUtils
 * Method:    split
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_info_narazaki_android_lib_list_ListUtils_split__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     info_narazaki_android_lib_list_ListUtils
 * Method:    split
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)[J
 */
JNIEXPORT jlongArray JNICALL Java_info_narazaki_android_lib_list_ListUtils_split__Ljava_lang_String_2Ljava_lang_String_2J
  (JNIEnv *, jclass, jstring, jstring, jlong);

/*
 * Class:     info_narazaki_android_lib_list_ListUtils
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_lib_list_ListUtils_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
