/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_tuboroid_data_ThreadEntryData */

#ifndef _Included_info_narazaki_android_tuboroid_data_ThreadEntryData
#define _Included_info_narazaki_android_tuboroid_data_ThreadEntryData
#ifdef __cplusplus
extern "C" {
#endif
#undef info_narazaki_android_tuboroid_data_ThreadEntryData_MAX_BACK_LINKS
#define info_narazaki_android_tuboroid_data_ThreadEntryData_MAX_BACK_LINKS 10L
#undef info_narazaki_android_tuboroid_data_ThreadEntryData_ANALYZE_PROGRESS_UI_THREAD
#define info_narazaki_android_tuboroid_data_ThreadEntryData_ANALYZE_PROGRESS_UI_THREAD 7L
#undef info_narazaki_android_tuboroid_data_ThreadEntryData_ANALYZE_PROGRESS_EXT_THREAD
#define info_narazaki_android_tuboroid_data_ThreadEntryData_ANALYZE_PROGRESS_EXT_THREAD 5L
#undef info_narazaki_android_tuboroid_data_ThreadEntryData_ANALYZE_PROGRESS_MAX
#define info_narazaki_android_tuboroid_data_ThreadEntryData_ANALYZE_PROGRESS_MAX 12L
/*
 * Class:     info_narazaki_android_tuboroid_data_ThreadEntryData
 * Method:    is2chAsciiArt
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_info_narazaki_android_tuboroid_data_ThreadEntryData_is2chAsciiArt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     info_narazaki_android_tuboroid_data_ThreadEntryData
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_tuboroid_data_ThreadEntryData_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
