/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_lib_text_HtmlUtils */

#ifndef _Included_info_narazaki_android_lib_text_HtmlUtils
#define _Included_info_narazaki_android_lib_text_HtmlUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_narazaki_android_lib_text_HtmlUtils
 * Method:    escapeHtml
 * Signature: (Ljava/lang/String;ZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_narazaki_android_lib_text_HtmlUtils_escapeHtml(JNIEnv *, jclass, jstring, jboolean,
        jstring);

/*
 * Class:     info_narazaki_android_lib_text_HtmlUtils
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_lib_text_HtmlUtils_initNative(JNIEnv *, jclass);

/*
 * Class:     info_narazaki_android_lib_text_HtmlUtils
 * Method:    stripAllHtmls
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_narazaki_android_lib_text_HtmlUtils_stripAllHtmls(JNIEnv *, jclass, jstring,
        jboolean);

/*
 * Class:     info_narazaki_android_lib_text_HtmlUtils
 * Method:    unescapeHtml
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_narazaki_android_lib_text_HtmlUtils_unescapeHtml(JNIEnv *, jclass, jstring);

/*
 * Class:     info_narazaki_android_lib_text_HtmlUtils
 * Method:    shrinkHtml
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_narazaki_android_lib_text_HtmlUtils_shrinkHtml(JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
