/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_lib_text_LevenshteinDistance */

#ifndef _Included_info_narazaki_android_lib_text_LevenshteinDistance
#define _Included_info_narazaki_android_lib_text_LevenshteinDistance
#ifdef __cplusplus
extern "C" {
#endif
#undef info_narazaki_android_lib_text_LevenshteinDistance_MAX_SIMILARITY_RATE
#define info_narazaki_android_lib_text_LevenshteinDistance_MAX_SIMILARITY_RATE 65535L
/*
 * Class:     info_narazaki_android_lib_text_LevenshteinDistance
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_info_narazaki_android_lib_text_LevenshteinDistance_diff(JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     info_narazaki_android_lib_text_LevenshteinDistance
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_lib_text_LevenshteinDistance_initNative(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
