/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_lib_text_span_WebURLFilter */

#ifndef _Included_info_narazaki_android_lib_text_span_WebURLFilter
#define _Included_info_narazaki_android_lib_text_span_WebURLFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_narazaki_android_lib_text_span_WebURLFilter
 * Method:    constructNative
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_info_narazaki_android_lib_text_span_WebURLFilter_constructNative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     info_narazaki_android_lib_text_span_WebURLFilter
 * Method:    destructNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_lib_text_span_WebURLFilter_destructNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     info_narazaki_android_lib_text_span_WebURLFilter
 * Method:    gatherNative
 * Signature: (Ljava/lang/String;J)[Linfo/narazaki/android/lib/text/span/SpanSpec;
 */
JNIEXPORT jobjectArray JNICALL Java_info_narazaki_android_lib_text_span_WebURLFilter_gatherNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     info_narazaki_android_lib_text_span_WebURLFilter
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_lib_text_span_WebURLFilter_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
