/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_lib_text_TextUtils */

#ifndef _Included_info_narazaki_android_lib_text_TextUtils
#define _Included_info_narazaki_android_lib_text_TextUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_narazaki_android_lib_text_TextUtils
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_narazaki_android_lib_text_TextUtils_initNative
  (JNIEnv *, jclass);

/*
 * Class:     info_narazaki_android_lib_text_TextUtils
 * Method:    parseInt
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_info_narazaki_android_lib_text_TextUtils_parseInt
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     info_narazaki_android_lib_text_TextUtils
 * Method:    parseLong
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_info_narazaki_android_lib_text_TextUtils_parseLong
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
