/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_narazaki_android_lib_view_NSimpleLayout */

#ifndef _Included_info_narazaki_android_lib_view_NSimpleLayout
#define _Included_info_narazaki_android_lib_view_NSimpleLayout
#ifdef __cplusplus
extern "C" {
#endif
#undef info_narazaki_android_lib_view_NSimpleLayout_LINES_I_START
#define info_narazaki_android_lib_view_NSimpleLayout_LINES_I_START 0L
#undef info_narazaki_android_lib_view_NSimpleLayout_LINES_I_FM_TOP
#define info_narazaki_android_lib_view_NSimpleLayout_LINES_I_FM_TOP 1L
#undef info_narazaki_android_lib_view_NSimpleLayout_LINES_I_FM_DESCENT
#define info_narazaki_android_lib_view_NSimpleLayout_LINES_I_FM_DESCENT 2L
#undef info_narazaki_android_lib_view_NSimpleLayout_LINES_I_WIDTH
#define info_narazaki_android_lib_view_NSimpleLayout_LINES_I_WIDTH 3L
#undef info_narazaki_android_lib_view_NSimpleLayout_LINES_I_MAX
#define info_narazaki_android_lib_view_NSimpleLayout_LINES_I_MAX 4L
#undef info_narazaki_android_lib_view_NSimpleLayout_FM_I_TOP
#define info_narazaki_android_lib_view_NSimpleLayout_FM_I_TOP 0L
#undef info_narazaki_android_lib_view_NSimpleLayout_FM_I_BOTTOM
#define info_narazaki_android_lib_view_NSimpleLayout_FM_I_BOTTOM 1L
#undef info_narazaki_android_lib_view_NSimpleLayout_FM_I_ASCENT
#define info_narazaki_android_lib_view_NSimpleLayout_FM_I_ASCENT 2L
#undef info_narazaki_android_lib_view_NSimpleLayout_FM_I_DESCENT
#define info_narazaki_android_lib_view_NSimpleLayout_FM_I_DESCENT 3L
#undef info_narazaki_android_lib_view_NSimpleLayout_FM_I_LEADING
#define info_narazaki_android_lib_view_NSimpleLayout_FM_I_LEADING 4L
#undef info_narazaki_android_lib_view_NSimpleLayout_FM_I_MAX
#define info_narazaki_android_lib_view_NSimpleLayout_FM_I_MAX 5L
/*
 * Class:     info_narazaki_android_lib_view_NSimpleLayout
 * Method:    generateNative
 * Signature: (Ljava/lang/String;I[I[F[I[FI)[I
 */
JNIEXPORT jintArray JNICALL Java_info_narazaki_android_lib_view_NSimpleLayout_generateNative
  (JNIEnv *, jobject, jstring, jint, jintArray, jfloatArray, jintArray, jfloatArray, jint);

/*
 * Class:     info_narazaki_android_lib_view_NSimpleLayout
 * Method:    checkSupportedNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_info_narazaki_android_lib_view_NSimpleLayout_checkSupportedNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
